# PCB Object Detection Training Configuration

# 모델 설정
model:
  type: yolov11s     # yolov5, yolov8, yolov11
  size: s           # n, s, m, l
  pretrained: true

# 데이터셋 설정
data:
  data_yaml: dataset/raw/data.yaml
  img_size: 600

# 학습 설정
training:
  epochs: 30 # baseline: 30
  batch_size: 16
  device: cuda      # cuda, cpu, 0, 1, 2, 3
  workers: 8

  # 최적화
  # optimizer: AdamW  # AdamW, SGD, Adam
  # lr0: 0.01         # 초기 학습률
  # lrf: 0.01         # 최종 학습률 (lr0 * lrf)
  # momentum: 0.937
  # weight_decay: 0.0005

  # Early stopping
  patience: 10

  # 저장 설정
  save_period: # 10   # N epoch마다 저장
  save_dir: outputs

# 데이터 증강
augmentation:
  enabled: False       # 증강 사용 여부
  pcb_optimized: False # PCB 특화 증강 사용 여부 (밝기/그림자/회전/반전 중심)
  exclude_classes: [] # 증강에서 제외할 클래스 (예: ['mouse_bite', 'spur'] 또는 [0, 1])

  # 아래 파라미터들은 나중에 세부 조정용 (현재는 코드 내 기본값 사용)
  # degrees: 10       # 회전 각도
  # translate: 0.1    # 이동
  # scale: 0.1        # 스케일
  # flipud: 0.3       # 상하 반전 확률
  # fliplr: 0.5       # 좌우 반전 확률

# Weights & Biases 설정
wandb:
  enabled: true     # wandb 사용 여부
  project: PCB_Detection
  name: yolo_V11_s-base

# 실험 설정
experiment:
  name: yolo_V11_s-base
  seed: 42
